### ISSUE TITLE
Engagement Metrics are showing an error

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/firefox-test-tube#203]
Didn't see a bug about this, so:

Engagement metric summary stats and confidence intervals are being shipped over, yay @jklukas!

It looks like these are on page 2 of metrics (which we should probably change and bump these to the top), but more importantly they're showing an error message, "Unsupported metric type: DoubleScalar":
https://firefox-test-tube.herokuapp.com/experiments/hotfix-http-throttling-v2-bug-1462906/?page=2

**Comment by jklukas** [comment]
Discussed this a bit with @sunahsuh. I introduced this new "DoubleScalar" type for the derived engagement metrics; it's not one of the client instrumentation types because these metrics don't correspond directly to a single client metric; they're derived ratios, so naturally floating point quantities.

Adding this new type is similar to the "ExperimentMetadata" type that already existed in the experiments_aggregates dataset.

**Comment by robhudson** [comment]
For the backend we need to update 2 things to get these to display:

1. The import. Currently these are getting imported as if they were histograms but there is no histogram data to import. So we will need to add a condition to treat these differently, probably triggering on the metric type of `DoubleScalar` or a fixed list of specific metric names.

2. The API. Once we have the data we will also need to update the API. Currently these get sent in the response of the metric API but they are empty. We can continue to do this in the metric API but may need a condition to send the mean values and confidence intervals instead of histogram data. The front-end would need updating accordingly to display the correct graph.

@spasovski Any other comments from the front-end perspective?

**Comment by openjck** [comment]
This should no longer be needed now that the front-end has been removed. Please reopen if I'm mistaken.
