### ISSUE TITLE
Exponential x-axis labelling for exponential metrics

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/firefox-test-tube#47]
Currently even the exponential histograms are showing up on graphs w a linear x-axis presentation, squishing all of the interesting data into the far left corner of the graph. We need the x axis to use exponential scaling to match the presentation we're seeing in experiments viewer.

**Comment by spasovski** [comment]
This is my current top priority but it's definitely difficult since we're unable to set our own D3 axis directly and all I can try is to define a new custom chart.js axis that fits its expected interface. If that approach ever fails we may have to rely on simply setting a logarithmic scale but it wouldn't look quite as clean as the ordinal scale currently in use by EV.
